# Generated by Django 4.0.3 on 2023-05-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='메뉴명')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('오넛지', '오넛지'), ('카츠', '카츠'), ('더푸리', '더푸리'), ('카페', '카페')], max_length=5)),
                ('image', models.ImageField(upload_to='menu/')),
            ],
        ),
    ]
