# Generated by Django 4.0.3 on 2023-04-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='ss_choice',
        ),
    ]
